name: UnitTest
on:
  push:
    branches: ['master']
    paths-ignore:
      - '**.md'
  pull_request:
    branches: ['master']
jobs:
  Perform-Unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: 'x64'
          cache: 'pip'
      - name: Update PIP
        run: python -m pip install --upgrade pip
      - name: Install Packages and Dependencies
        run: pip install -r requirements.txt
      - name: Run Unittests (nose2)
        run: nose2 -v